import React from 'react';
export const en = {
  all: 'All Rooms',
  final_cleaned: 'Final Cleaned',
  cleaned:'Cleaned',
  uncleaned:'Uncleaned',
  maintenance:'Maintenance',
  room:'Room',
  property:'Property',
  Clean_Room:'Clean Room',
  Report_Mainteance:'Report Maintenance issue',
  View_maintenance:'See Maintenance issue',
  Additional_comments:'Additional comments',
  repaired:'Repaired',
  working_on:'Working on',
  supplies:'Supplies',
  other:'Other',
  Send:'Send',
  problem:'Problem',
  final_clean:'Final Clean',
  pending:'pending',
  total_maintenance : 'Total maintenance issues',
  finalCleanBy : 'Final Cleaned By',
  cleanBy : 'Cleaned By',
  uncleanBy :'Unclean By',
  status : 'Status',
  reportatedBy :'Reported by',
  reportatedDate :'Reported date',
  housekeeper :'Housekeeper',
  head_housekeeper :'Head Housekeeper',
  maintenance : 'Maintenance',
  front_desk : 'Frontdesk',
  repairedBy:'Repaired By',
  repairedDate:'Repaired Date',
  status_description:'Status Description',
  assignTo:'Assign To',
  assigned:'Assign Room',
  };
export const es = {
  all: 'Todos',
  final_cleaned: 'Final Limpiado',
  cleaned:'limpiado',
  uncleaned:'Sucia',
  maintenance:'Mantenimeinto',
  room:'Habitación',
  property:'Propiedad',
  Clean_Room:'Sala Limpia',
  Report_Mainteance:'Informe de Mantenimieto',
  View_maintenance:'Ver Problema de mantenimiento',
  Additional_comments:'Comentario adicional',
  repaired:'Reparado',
  working_on:'Trabajandoen',
  supplies:'Suministros',
  other:'Otra',
  Send:'Enviar',
  problem:'Problema',
  final_clean:'Limpieza Final',
  pending:'pending',
  total_maintenance : 'Problemas de mantenimiento',
  finalCleanBy : 'Final Limpiado por',
  cleanBy : 'Limpiado por',
  uncleanBy :'Unclean By',
  status : 'Estado',
  reportatedBy :'Reportado por',
  housekeeper :'Housekeeper',
  head_housekeeper :'Head Housekeeper',
  maintenance : 'Maintenance',
  front_desk : 'Frontdesk',
  repairedBy:'Repaired By',
  repairedDate:'Repaired Date',
  status_description:'Status Description',
  assignTo:'Assign To',
  assigned:'Assign Room',
  };